[package]
name = "gp-geometry"
description = "Computational geometry on the plane and the ellipsoid."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.geoprims]
module = "geometry"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gp-base.workspace = true
