[package]
name = "gp-indexing"
description = "Spatial indexing: H3, S2, geohash, tiles, Plus Codes."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.geoprims]
module = "indexing"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gp-base.workspace = true
gp-geo = { path = "../gp-geo" }
libm.workspace = true

[dev-dependencies]
serde_json.workspace = true
