//! S2 parity: the port against s2sphere, the Python implementation of the same
//! algorithms, on 400 cases spread over the sphere and every kind of level.
//! The fixture is generated by tools/vectors/gen_s2.py.

use gp_indexing::s2::CellId;
use serde_json::Value;

#[test]
fn matches_s2sphere_on_every_case() {
    let text = include_str!("data/s2_parity.jsonl");
    let (mut n, mut worst_center, mut worst_vertex, mut worst_area) = (0, 0.0f64, 0.0f64, 0.0f64);
    for line in text.lines().filter(|l| !l.trim().is_empty()) {
        let v: Value = serde_json::from_str(line).expect("fixture is JSON");
        let (lat, lon) = (v["lat"].as_f64().unwrap(), v["lon"].as_f64().unwrap());
        let level = v["level"].as_u64().unwrap() as u8;
        let want = v["token"].as_str().unwrap();
        let cell = CellId::from_lat_lon(lat, lon, level);
        assert_eq!(cell.token(), want, "token at {lat},{lon} level {level}");
        assert_eq!(cell.level(), level);
        assert_eq!(CellId::from_token(want).unwrap(), cell, "token round trip");

        // Centers and vertices, in meters on a sphere of the Earth's radius.
        let meters = |(a, b): (f64, f64), (c, d): (f64, f64)| {
            let (a, b, c, d) = (
                a.to_radians(),
                b.to_radians(),
                c.to_radians(),
                d.to_radians(),
            );
            let h =
                ((c - a) / 2.0).sin().powi(2) + a.cos() * c.cos() * ((d - b) / 2.0).sin().powi(2);
            2.0 * 6_371_008.8 * h.sqrt().asin()
        };
        let c = v["center"].as_array().unwrap();
        let d = meters(
            cell.center(),
            (c[0].as_f64().unwrap(), c[1].as_f64().unwrap()),
        );
        worst_center = worst_center.max(d);
        for (k, got) in cell.vertices().iter().enumerate() {
            let w = v["vertices"][k].as_array().unwrap();
            let d = meters(*got, (w[0].as_f64().unwrap(), w[1].as_f64().unwrap()));
            worst_vertex = worst_vertex.max(d);
        }
        // Edge neighbours, in the same order.
        let want_n: Vec<&str> = v["neighbors"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_str().unwrap())
            .collect();
        let got_n: Vec<String> = cell.edge_neighbors().iter().map(|c| c.token()).collect();
        assert_eq!(got_n, want_n, "edge neighbours of {want}");
        // Exact area. The two agree to rounding at coarse levels and drift to
        // about 2e-7 relative at level 30, where a cell is a centimeter across
        // and its corners differ in the last bits of a unit vector; the
        // absolute difference there is a millionth of a square micrometer.
        let want_area = v["area"].as_f64().unwrap();
        let got_area = cell.area_steradians();
        let rel = (got_area / want_area - 1.0).abs();
        worst_area = worst_area.max(rel);
        if level <= 20 {
            assert!(rel < 1e-9, "area at level {level}: {rel} relative");
        }

        n += 1;
    }
    println!(
        "{n} cases: worst center {worst_center:.3e} m, vertex {worst_vertex:.3e} m, area {worst_area:.3e}"
    );
    assert!(n >= 400, "only {n} cases");
    // Both implementations do the same arithmetic in double precision, so the
    // geometry agrees to within rounding rather than approximately.
    assert!(worst_center < 1e-6, "worst center {worst_center} m");
    assert!(worst_vertex < 1e-6, "worst vertex {worst_vertex} m");
    assert!(worst_area < 1e-6, "worst area {worst_area} relative");
}
