-- 0001_problem_reports.sql: generated by tools/codegen/d1-migration.mjs from
-- data/report-limits.json. Do not edit; change the limits file and regenerate.
CREATE TABLE problem_reports (
  id TEXT PRIMARY KEY NOT NULL,
  created_at TEXT NOT NULL,
  tool_id TEXT NOT NULL,
  tool_version TEXT NOT NULL,
  core_version TEXT NOT NULL,
  build_hash TEXT NOT NULL,
  asset_versions_json TEXT NOT NULL CHECK (length(asset_versions_json) <= 2000),
  kind TEXT NOT NULL CHECK (kind IN ('wrong-result','broken','confusing','other')),
  page_path TEXT NOT NULL CHECK (length(page_path) <= 2048),
  note TEXT CHECK (note IS NULL OR length(note) <= 280),
  note_has_url INTEGER NOT NULL DEFAULT 0 CHECK (note_has_url IN (0,1)),
  inputs_json TEXT NOT NULL CHECK (length(inputs_json) <= 12000),
  outputs_json TEXT NOT NULL CHECK (length(outputs_json) <= 12000),
  warnings_json TEXT NOT NULL CHECK (length(warnings_json) <= 2000),
  display_json TEXT NOT NULL CHECK (length(display_json) <= 300),
  dedupe_key TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN
    ('open','triaged','confirmed','fixed','wont_fix','duplicate','not_a_bug')),
  primary_source TEXT CHECK (primary_source IS NULL OR length(primary_source) <= 1000),
  resolution_note TEXT CHECK (resolution_note IS NULL OR length(resolution_note) <= 1000),
  fixed_in_version TEXT,
  resolved_at TEXT
);
CREATE INDEX pr_status_kind_created ON problem_reports (status, kind, created_at);
CREATE INDEX pr_tool_status ON problem_reports (tool_id, status);
CREATE TABLE report_limits (
  bucket TEXT NOT NULL,
  scope TEXT NOT NULL CHECK (scope IN ('global','reporter')),
  subject TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('attempt','accepted')),
  count INTEGER NOT NULL CHECK (count >= 0),
  PRIMARY KEY (bucket, scope, subject, kind)
) WITHOUT ROWID;
