#!/usr/bin/env python3
"""Compacts Bird's PB2002 orogens (diffuse plate-boundary deformation zones)
into core/crates/gp-geo/data/orogens.txt for the DEFORMATION_ZONE flag.

Source: P. Bird, "An updated digital model of plate boundaries", G3 4(3) 1027,
2003, as GeoJSON in github.com/fraxen/tectonicplates (ODC-BY 1.0). Usage:
  curl -sLO https://raw.githubusercontent.com/fraxen/tectonicplates/master/GeoJSON/PB2002_orogens.json
  python3 tools/codegen/orogens.py PB2002_orogens.json
Each zone is a line "# name" followed by one ring per line of "lon,lat" pairs.
"""
import json
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "core/crates/gp-geo/data/orogens.txt"


def main(path):
    d = json.load(open(path))
    lines = ["# PB2002 orogens (Bird 2003), ODC-BY 1.0; generated by tools/codegen/orogens.py"]
    for f in d["features"]:
        g = f["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        lines.append(f"@ {f['properties']['Name']}")
        for poly in polys:
            ring = poly[0]
            lines.append(" ".join(f"{lon:.4f},{lat:.4f}" for lon, lat in ring))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(OUT, len(d["features"]), "zones")


if __name__ == "__main__":
    main(sys.argv[1])
