#!/usr/bin/env python3
"""Generates core/crates/gp-geo/src/spcs83_zones.rs: all 124 SPCS83 zones from
the EPSG dataset (via pyproj/PROJ), with the NGS zone code, projection
parameters, the feet unit EPSG defines for the zone (US survey or
international), and the zone's area-of-use box. Needs pyproj in a scratch
virtualenv. Rerunning must reproduce the file.
"""
import re
import sys
from pathlib import Path

import pyproj
from pyproj.database import query_crs_info

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "core/crates/gp-geo/src/spcs83_zones.rs"
# EPSG conversion codes are 1 + state (2) + series digit + zone; these differ.
FIPS_OVERRIDES = {"NAD83 / Kentucky North": "1601"}


def lit(x):
    r = repr(float(x))
    return r if ("." in r or "e" in r) else r + ".0"


def main():
    names = {i.name: i for i in query_crs_info(auth_name="EPSG", pj_types=["PROJECTED_CRS"]) if not i.deprecated}
    rows = []
    for i in names.values():
        if not i.name.startswith("NAD83 / "):
            continue
        c = pyproj.CRS.from_epsg(int(i.code))
        op = c.coordinate_operation
        if op is None or not re.match(r"^SPCS83 .*\(meters?\)$", op.name):
            continue
        code = str(op.to_json_dict()["id"]["code"])[1:]
        fips = FIPS_OVERRIDES.get(i.name, code[:2] + code[3:].zfill(2))
        p = {x.name: x.value for x in op.params}
        m = op.method_name
        if m == "Transverse Mercator":
            proj = (f"Proj::Tm {{ lat0: {lit(p['Latitude of natural origin'])}, lon0: {lit(p['Longitude of natural origin'])}, "
                    f"k0: {lit(p['Scale factor at natural origin'])}, fe: {lit(p['False easting'])}, fn_: {lit(p['False northing'])} }}")
        elif m == "Lambert Conic Conformal (2SP)":
            proj = (f"Proj::Lcc {{ lat0: {lit(p['Latitude of false origin'])}, lon0: {lit(p['Longitude of false origin'])}, "
                    f"lat1: {lit(p['Latitude of 1st standard parallel'])}, lat2: {lit(p['Latitude of 2nd standard parallel'])}, "
                    f"fe: {lit(p['Easting at false origin'])}, fn_: {lit(p['Northing at false origin'])} }}")
        elif m == "Hotine Oblique Mercator (variant A)":
            proj = (f"Proj::OmercA {{ latc: {lit(p['Latitude of projection centre'])}, lonc: {lit(p['Longitude of projection centre'])}, "
                    f"alpha: {lit(p['Azimuth of initial line'])}, gamma: {lit(p['Angle from Rectified to Skew Grid'])}, "
                    f"k0: {lit(p['Scale factor on initial line'])}, fe: {lit(p['False easting'])}, fn_: {lit(p['False northing'])} }}")
        else:
            raise SystemExit(f"unexpected method {m} for {i.name}")
        base = i.name
        feet = "Some(\"ftUS\")" if f"{base} (ftUS)" in names else ("Some(\"ft\")" if f"{base} (ft)" in names else "None")
        b = c.area_of_use.bounds
        zone = op.name.removeprefix("SPCS83 ").removesuffix(" (meters)").removesuffix(" (meter)")
        rows.append((fips, f'    Zone {{ fips: "{fips}", epsg: {i.code}, name: "{zone}", proj: {proj}, feet: {feet}, '
                           f'bbox: [{lit(b[0])}, {lit(b[1])}, {lit(b[2])}, {lit(b[3])}] }},'))
    rows.sort()
    assert len(rows) == 124, len(rows)
    assert len({r[0] for r in rows}) == 124
    head = (f"// Generated by tools/codegen/spcs83.py from the EPSG dataset in PROJ {pyproj.proj_version_str}. Do not edit.\n"
            "use crate::spcs::{Proj, Zone};\n\n"
            "#[rustfmt::skip]\npub const ZONES: &[Zone] = &[\n")
    OUT.write_text(head + "\n".join(r[1] for r in rows) + "\n];\n")
    print(f"wrote {OUT} ({len(rows)} zones)", file=sys.stderr)


if __name__ == "__main__":
    main()
