[package]
name = "gp-navigation"
description = "Navigation: geodesics, routes, line of sight, 3D vectors."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.geoprims]
module = "navigation"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gp-base.workspace = true
gp-geo = { path = "../gp-geo" }
geographiclib-rs = "0.2.7"
libm.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde_json.workspace = true
