#!/usr/bin/env python3
"""Golden vectors for the Helmert and ITRF tools (geodesy/datums-and-transformations).

Sources: the worked examples of IOGP Guidance Note 7-2 (§4.2.3, §4.2.5), and
PROJ's own Helmert operator (+proj=helmert) through pyproj for random
parameter sets and for ITRF chains. The ITRF parameters below are PROJ's
data/ITRF2020 file (generated by PROJ from the EPSG dataset, which carries
the IERS values), kept here so the vectors are reproducible offline.

Writes core/vectors/geodesy.datum.{helmert,itrf}.jsonl.
"""
import json
import random
from pathlib import Path

from pyproj import Transformer

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "core/vectors"
GN72 = ("IOGP Guidance Note 7-2 worked example", "IOGP 373-7-2, September 2019")
PROJ = ("PROJ +proj=helmert through pyproj", "PROJ 9.3 (pyproj 3.6)")
PROJ_ITRF = ("PROJ +proj=helmert with PROJ's ITRF2020 parameter file, through pyproj", "PROJ 9.3 (pyproj 3.6); data/ITRF2020")
RULES = ("add-geodesy-suite input rules", "2026-09")

# PROJ data/ITRF2020 (ITRF2020 to past ITRFs, position vector, epoch 2015).
ITRF2020 = {
    "ITRF2014": "+x=-0.0014 +y=-0.0009 +z=0.0014 +s=-0.00042 +dy=-0.0001 +dz=0.0002 +t_epoch=2015 +convention=position_vector",
    "ITRF2008": "+x=0.0002 +y=0.001 +z=0.0033 +s=-0.00029 +dy=-0.0001 +dz=0.0001 +ds=3e-05 +t_epoch=2015 +convention=position_vector",
    "ITRF2005": "+x=0.0027 +y=0.0001 +z=-0.0014 +s=0.00065 +dx=0.0003 +dy=-0.0001 +dz=0.0001 +ds=3e-05 +t_epoch=2015 +convention=position_vector",
    "ITRF2000": "+x=-0.0002 +y=0.0008 +z=-0.0342 +s=0.00225 +dx=0.0001 +dz=-0.0017 +ds=0.00011 +t_epoch=2015 +convention=position_vector",
    "ITRF97": "+x=0.0065 +y=-0.0039 +z=-0.0779 +rz=0.00036 +s=0.00398 +dx=0.0001 +dy=-0.0006 +dz=-0.0031 +drz=2e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
    "ITRF96": "+x=0.0065 +y=-0.0039 +z=-0.0779 +rz=0.00036 +s=0.00398 +dx=0.0001 +dy=-0.0006 +dz=-0.0031 +drz=2e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
    "ITRF94": "+x=0.0065 +y=-0.0039 +z=-0.0779 +rz=0.00036 +s=0.00398 +dx=0.0001 +dy=-0.0006 +dz=-0.0031 +drz=2e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
    "ITRF93": "+x=-0.0658 +y=0.0019 +z=-0.0713 +rx=-0.00336 +ry=-0.00433 +rz=0.00075 +s=0.00447 +dx=-0.0028 +dy=-0.0002 +dz=-0.0023 +drx=-0.00011 +dry=-0.00019 +drz=7e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
    "ITRF92": "+x=0.0145 +y=-0.0019 +z=-0.0859 +rz=0.00036 +s=0.00327 +dx=0.0001 +dy=-0.0006 +dz=-0.0031 +drz=2e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
    "ITRF91": "+x=0.0265 +y=0.0121 +z=-0.0919 +rz=0.00036 +s=0.00467 +dx=0.0001 +dy=-0.0006 +dz=-0.0031 +drz=2e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
    "ITRF90": "+x=0.0245 +y=0.0081 +z=-0.1079 +rz=0.00036 +s=0.00497 +dx=0.0001 +dy=-0.0006 +dz=-0.0031 +drz=2e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
    "ITRF89": "+x=0.0295 +y=0.0321 +z=-0.1459 +rz=0.00036 +s=0.00837 +dx=0.0001 +dy=-0.0006 +dz=-0.0031 +drz=2e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
    "ITRF88": "+x=0.0245 +y=-0.0039 +z=-0.1699 +rx=0.0001 +rz=0.00036 +s=0.01147 +dx=0.0001 +dy=-0.0006 +dz=-0.0031 +drz=2e-05 +ds=0.00012 +t_epoch=2015 +convention=position_vector",
}
WGS84 = {"WGS84(G2296)": "ITRF2020", "WGS84(G2139)": "ITRF2014", "WGS84(G1762)": "ITRF2008", "WGS84": "ITRF2020"}


def vec(i, inp, exp, src, tol=None, ok=True):
    e = dict(exp)
    e["ok"] = ok
    v = {"id": f"v{i:03d}", "input": inp, "expect": e, "source": src[0], "sourceVersion": src[1]}
    if tol:
        v["tolerance"] = tol
    return v


def write(name, vs):
    (OUT / f"{name}.jsonl").write_text("".join(json.dumps(v, ensure_ascii=False, separators=(",", ":")) + "\n" for v in vs))
    print(name, len(vs))


def xyz_tol(t):
    return {f"result.{k}.value": {"abs": t} for k in "xyz"}


def helmert():
    vs = []
    # GN 7-2 §4.2.3, both conventions (published to the centimeter).
    src = {"x": 3657660.66, "y": 255768.55, "z": 5201382.11}
    want = {"result.x.value": 3657660.78, "result.y.value": 255778.43, "result.z.value": 5201387.75}
    vs.append(vec(1, {**src, "tz": 4.5, "rz": 0.554, "scale": 0.219, "convention": "position-vector"}, want, GN72, xyz_tol(0.01)))
    vs.append(vec(2, {**src, "tz": 4.5, "rz": -0.554, "scale": 0.219, "convention": "coordinate-frame"}, want, GN72, xyz_tol(0.01)))
    # §4.2.5: ITRF2008 → GDA94 at 2013.90 (published to the millimeter), and its reverse.
    td = {"tx": "-84.68 mm", "ty": "-19.42 mm", "tz": "32.01 mm", "rx": "-0.4254 mas", "ry": "2.2578 mas", "rz": "2.4015 mas", "scale": "0.00971 ppm",
          "tx_rate": "1.42 mm/yr", "ty_rate": "1.34 mm/yr", "tz_rate": "0.90 mm/yr", "rx_rate": "1.5461 mas/yr", "ry_rate": "1.1820 mas/yr", "rz_rate": "1.1551 mas/yr",
          "scale_rate": "0.000109 ppm/yr", "reference_epoch": 1994.0, "epoch": "2013.90", "convention": "coordinate-frame"}
    vs.append(vec(3, {"x": -3789470.710, "y": 4841770.404, "z": -1690893.952, **td},
                  {"result.x.value": -3789470.004, "result.y.value": 4841770.686, "result.z.value": -1690895.108}, GN72, xyz_tol(0.0006)))
    vs.append(vec(4, {"x": -3789470.004, "y": 4841770.686, "z": -1690895.108, **td, "direction": "reverse"},
                  {"result.x.value": -3789470.710, "result.y.value": 4841770.404, "result.z.value": -1690893.952}, GN72, xyz_tol(0.0006)))
    # Random parameter sets through PROJ, both conventions, with and without rates, forward and inverse.
    rnd = random.Random(20260919)
    i = 5
    for k in range(18):
        conv = ["position_vector", "coordinate_frame"][k % 2]
        p = {"x": rnd.uniform(-300, 300), "y": rnd.uniform(-300, 300), "z": rnd.uniform(-300, 300),
             "rx": rnd.uniform(-5, 5), "ry": rnd.uniform(-5, 5), "rz": rnd.uniform(-5, 5), "s": rnd.uniform(-20, 20)}
        rates = k % 3 == 0
        if rates:
            p.update({"dx": rnd.uniform(-0.01, 0.01), "dy": rnd.uniform(-0.01, 0.01), "dz": rnd.uniform(-0.01, 0.01),
                      "drx": rnd.uniform(-0.01, 0.01), "dry": rnd.uniform(-0.01, 0.01), "drz": rnd.uniform(-0.01, 0.01), "ds": rnd.uniform(-0.01, 0.01)})
        t0, t = 2010.0, round(rnd.uniform(1995, 2030), 3)
        pipe = "+proj=helmert " + " ".join(f"+{k2}={v!r}" for k2, v in p.items()) + f" +convention={conv}" + (f" +t_epoch={t0}" if rates else "")
        # The reverse is the exact inverse (GN 7-2 "Reversibility"); PROJ's
        # inverse transposes the linearized matrix, which differs at second
        # order in the rotations, so reverse cases invert PROJ's forward instead.
        reverse = k % 4 == 1
        tr = Transformer.from_pipeline(pipe)
        lat, lon = rnd.uniform(-80, 80), rnd.uniform(-180, 180)
        import math
        r = 6378137 + rnd.uniform(-5000, 9000)
        x0 = [r * math.cos(math.radians(lat)) * math.cos(math.radians(lon)), r * math.cos(math.radians(lat)) * math.sin(math.radians(lon)), r * math.sin(math.radians(lat))]
        out = tr.transform(*x0, t) if rates else tr.transform(*x0)
        inp = {"x": x0[0], "y": x0[1], "z": x0[2], "tx": p["x"], "ty": p["y"], "tz": p["z"], "rx": p["rx"], "ry": p["ry"], "rz": p["rz"], "scale": p["s"],
               "convention": conv.replace("_", "-")}
        if rates:
            inp.update({"tx_rate": p["dx"], "ty_rate": p["dy"], "tz_rate": p["dz"], "rx_rate": p["drx"], "ry_rate": p["dry"], "rz_rate": p["drz"],
                        "scale_rate": f"{p['ds']!r} ppm/yr", "reference_epoch": t0, "epoch": str(t)})
        exp = {"result.x.value": out[0], "result.y.value": out[1], "result.z.value": out[2]}
        if reverse:
            inp.update({"x": out[0], "y": out[1], "z": out[2], "direction": "reverse"})
            exp = {"result.x.value": x0[0], "result.y.value": x0[1], "result.z.value": x0[2]}
        vs.append(vec(i, inp, exp, PROJ, xyz_tol(1e-6))); i += 1
    # "Convention required", and rates without their epochs.
    vs.append(vec(i, {**src, "rz": 0.554}, {"error.code": "INVALID_INPUT", "error.field": "/convention"}, RULES, ok=False)); i += 1
    vs.append(vec(i, {**src, "tx_rate": 0.001, "convention": "position-vector"}, {"error.code": "INVALID_INPUT", "error.field": "/epoch"}, RULES, ok=False))
    write("geodesy.datum.helmert", vs)


def itrf():
    rnd = random.Random(7)
    vs = []
    frames = list(ITRF2020) + ["ITRF2020"]
    cart = "+step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=cart +ellps=GRS80"
    uncart = "+step +inv +proj=cart +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg"

    def chain(a, b):
        a, b = WGS84.get(a, a), WGS84.get(b, b)
        steps = ""
        if a != "ITRF2020":
            steps += f" +step +inv +proj=helmert {ITRF2020[a]}"
        if b != "ITRF2020":
            steps += f" +step +proj=helmert {ITRF2020[b]}"
        return steps

    cases = [("ITRF2020", "ITRF2014", 40.446111, -79.982222, 300, 2026.72), ("ITRF2014", "ITRF2020", -33.8688, 151.2093, 50, 2020.0),
             ("ITRF2020", "ITRF88", 64.1466, -21.9426, 10, 1990.5), ("ITRF93", "ITRF2008", 35.0, 139.0, 0, 2000.0),
             ("WGS84(G2139)", "ITRF2020", 51.47, -0.45, 20, 2024.1), ("ITRF2020", "WGS84(G1762)", -1.0, 36.8, 1700, 2011.0)]
    for _ in range(14):
        a, b = rnd.sample(frames, 2)
        cases.append((a, b, round(rnd.uniform(-85, 85), 6), round(rnd.uniform(-180, 179.9), 6), round(rnd.uniform(-50, 4000), 2), round(rnd.uniform(1985, 2035), 2)))
    for i, (a, b, lat, lon, h, t) in enumerate(cases, 1):
        steps = chain(a, b)
        geo = Transformer.from_pipeline(f"+proj=pipeline {cart}{steps} {uncart}").transform(lon, lat, h, t)
        ecef = Transformer.from_pipeline(f"+proj=pipeline {cart}{steps}").transform(lon, lat, h, t)
        exp = {"result.lat.value": geo[1], "result.lon.value": geo[0], "result.height.value": geo[2],
               "result.x.value": ecef[0], "result.y.value": ecef[1], "result.z.value": ecef[2]}
        tol = {"result.lat.value": {"abs": 1e-10}, "result.lon.value": {"abs": 1e-10}, **{f"result.{k}.value": {"abs": 1e-5} for k in ("height", "x", "y", "z")}}
        vs.append(vec(i, {"from": a, "to": b, "epoch": str(t), "lat": lat, "lon": lon, "height": h}, exp, PROJ_ITRF, tol))
    i = len(vs) + 1
    # ECEF input.
    x = Transformer.from_pipeline(f"+proj=pipeline {cart}").transform(-105.0, 40.0, 1600.0)
    ecef = Transformer.from_pipeline(f"+proj=pipeline +step +proj=helmert {ITRF2020['ITRF2014']}").transform(*x, 2026.0)
    vs.append(vec(i, {"from": "ITRF2020", "to": "ITRF2014", "epoch": "2026-01-01", "x": x[0], "y": x[1], "z": x[2]},
                  {"result.x.value": ecef[0], "result.y.value": ecef[1], "result.z.value": ecef[2]}, PROJ_ITRF, {f"result.{k}.value": {"abs": 1e-5} for k in "xyz"})); i += 1
    # "Coincidence stated": WGS 84 (G2296) and ITRF2020 are the same coordinates.
    vs.append(vec(i, {"from": "WGS84(G2296)", "to": "ITRF2020", "epoch": "2026.7", "lat": 38.5, "lon": -98.0, "height": 500},
                  {"result.shift.value": 0, "result.lat.value": 38.5, "result.lon.value": -98.0}, ("add-geodesy-suite scenario: coincidence stated", "2026-09"),
                  {"result.shift.value": {"abs": 1e-9}, "result.lat.value": {"abs": 1e-11}, "result.lon.value": {"abs": 1e-11}})); i += 1
    # "WGS84" unqualified assumes G2296.
    vs.append(vec(i, {"from": "WGS84", "to": "ITRF2020", "epoch": "2026.7", "lat": 38.5, "lon": -98.0},
                  {"meta.warnings.*.code": "REALIZATION_ASSUMED", "result.shift.value": 0}, ("add-geodesy-suite scenario: unqualified WGS 84", "2026-09"),
                  {"result.shift.value": {"abs": 1e-9}})); i += 1
    vs.append(vec(i, {"from": "ITRF2020", "to": "ITRF2014", "epoch": "1850", "lat": 0, "lon": 0}, {"error.code": "OUT_OF_DOMAIN"}, RULES, ok=False)); i += 1
    vs.append(vec(i, {"from": "ITRF2020", "to": "ITRF2014", "epoch": "2026.7"}, {"error.code": "INVALID_INPUT"}, RULES, ok=False))
    write("geodesy.datum.itrf", vs)


PMM = {  # PROJ data/ITRF2020 plate rotation rates (arcsec/yr)
    "NOAM": (0.000045, -0.000666, -0.000098), "PCFC": (-0.000404, 0.001021, -0.002154), "EURA": (-0.000085, -0.000519, 0.000753),
    "AUST": (0.001487, 0.001175, 0.001223), "SOAM": (-0.000261, -0.000282, -0.000157), "NUBI": (0.000090, -0.000585, 0.000717),
    "INDI": (0.001137, 0.000013, 0.001444), "ANTA": (-0.000269, -0.000312, 0.000678), "ARAB": (0.001129, -0.000146, 0.001438),
}
PROJ_PMM = ("PROJ +proj=helmert with the ITRF2020 plate motion rates of its data/ITRF2020, through pyproj", "PROJ 9.3 (pyproj 3.6); data/ITRF2020")


def plate_motion():
    import math
    cart = "+step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=cart +ellps=GRS80"
    uncart = "+step +inv +proj=cart +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg"
    cases = [("NOAM", 38.5, -98.0, 500, 2010.0, 2026.7, True), ("PCFC", 21.3, -157.8, 10, 2015.0, 2026.0, True), ("EURA", 48.85, 2.35, 60, 2000.0, 2026.7, True),
             ("AUST", -35.3, 149.1, 580, 1994.0, 2020.0, False), ("SOAM", -15.8, -47.9, 1100, 2010.0, 2030.0, True), ("NUBI", -26.2, 28.0, 1750, 2005.0, 2025.0, False),
             ("INDI", 20.0, 78.0, 300, 2012.0, 2026.0, True), ("ANTA", -77.8, 166.7, 20, 2000.0, 2020.0, True), ("ARAB", 24.7, 46.7, 600, 2010.0, 2026.7, True)]
    rnd = random.Random(3)
    for _ in range(10):
        pl = rnd.choice(list(PMM))
        cases.append((pl, round(rnd.uniform(-60, 60), 5), round(rnd.uniform(-180, 179), 5), round(rnd.uniform(0, 3000), 1), round(rnd.uniform(1990, 2020), 2), round(rnd.uniform(2020, 2035), 2), rnd.random() < 0.5))
    vs = []
    for i, (pl, lat, lon, h, t1, t2, orb) in enumerate(cases, 1):
        w = PMM[pl]
        hel = f"+proj=helmert +drx={w[0]} +dry={w[1]} +drz={w[2]}" + (" +dx=0.00037 +dy=0.00035 +dz=0.00074" if orb else "") + f" +t_epoch={t1} +convention=position_vector"
        geo = Transformer.from_pipeline(f"+proj=pipeline {cart} +step {hel} {uncart}").transform(lon, lat, h, t2)
        exp = {"result.lat.value": geo[1], "result.lon.value": geo[0], "result.height.value": geo[2]}
        tol = {"result.lat.value": {"abs": 1e-10}, "result.lon.value": {"abs": 1e-10}, "result.height.value": {"abs": 1e-5}}
        inp = {"lat": lat, "lon": lon, "height": h, "from_epoch": str(t1), "to_epoch": str(t2), "plate": pl}
        if not orb:
            inp["origin_rate"] = "no"
        vs.append(vec(i, inp, exp, PROJ_PMM, tol))
    i = len(vs) + 1
    # A site velocity replaces the model: 20 mm/yr east for 10 years is 0.2 m east.
    vs.append(vec(i, {"lat": 40, "lon": -105, "from_epoch": "2016.0", "to_epoch": "2026.0", "v_east": "20 mm/yr", "v_north": "-5 mm/yr", "v_up": "1 mm/yr"},
                  {"result.east.value": 0.2, "result.north.value": -0.05, "result.up.value": 0.01, "result.displacement.value": math.hypot(0.2, 0.05)},
                  ("Site velocity times elapsed time (definition)", "2026-09"), {k: {"abs": 1e-9} for k in ("result.east.value", "result.north.value", "result.up.value", "result.displacement.value")})); i += 1
    # "Propagation in a deformation zone": near the San Andreas fault.
    vs.append(vec(i, {"lat": 35.0, "lon": -119.5, "from_epoch": "2010.0", "to_epoch": "2026.7", "plate": "NOAM"}, {"meta.warnings.*.code": "DEFORMATION_ZONE"},
                  ("add-geodesy-suite scenario: propagation in a deformation zone", "2026-09"))); i += 1
    vs.append(vec(i, {"lat": 40, "lon": -105, "from_epoch": "2010.0", "to_epoch": "2026.7"}, {"error.code": "INVALID_INPUT", "error.field": "/plate"}, RULES, ok=False))
    write("geodesy.datum.plate-motion", vs)


if __name__ == "__main__":
    helmert()
    itrf()
    plate_motion()
