[package]
name = "gp-time"
description = "Time: sun position, twilight, time scales."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.geoprims]
module = "time"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gp-base.workspace = true
gp-geo = { path = "../gp-geo" }
libm.workspace = true

[dev-dependencies]
serde_json.workspace = true
