[package]
name = "gp-units"
description = "The base module: gp-base plus the units domain."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.geoprims]
module = "base"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gp-base.workspace = true
