//! Byte-for-byte agreement with `JSON.stringify` on ~12,000 doubles generated by
//! Node (see fixtures/gen-ecmascript-numbers.mjs).

use gp_base::num::format_f64;

#[test]
fn matches_node_json_stringify() {
    let text = include_str!("fixtures/ecmascript-numbers.txt");
    let mut n = 0;
    for line in text.lines() {
        let (hex, want) = line.split_once(' ').expect("fixture line");
        let x = f64::from_bits(u64::from_str_radix(hex, 16).expect("hex bits"));
        assert_eq!(format_f64(x).as_deref(), Some(want), "bits {hex}");
        n += 1;
    }
    assert!(n > 10_000, "fixture has {n} rows");
}
